## CMAKE_DOCUMENTATION_START FindMatlab.cmake
## WARNING: the standard FindMatlab.cmake module provided by cmake (3.x) is depracted \\n
## Provide : \\n
##	* MATLAB_EXECUTABLE cmake cache variable \\n
##	* MATLAB_RC_DIR		cmake cache variable \\n
##	* MATLAB_FOUND		[ON|OFF] \\n
##	* MATLAB_RC_FOUND	[ON|OFF] \\n
## Created/updated by jesnault
## CMAKE_DOCUMENTATION_END
if(WIN32)
	
	## in fact under windows matlab is already in the PATH, so we just need to check we have an installation
	set(PROGRAMFILES32 	  "PROGRAMFILES(x86)")
	file(GLOB MATLAB_DIRS "$ENV{PROGRAMFILES}/MATLAB/*")
	IF(NOT MATLAB_DIRS)
		file(GLOB MATLAB_DIRS "$ENV{${PROGRAMFILES32}}/MATLAB/*")
		IF(NOT MATLAB_DIRS)
			file(GLOB MATLAB_DIRS "$ENV{ProgramW6432}/MATLAB/*")
		ENDIF()
	ENDIF()
	if(MATLAB_DIRS)	
		## first looking for "MATLAB Component Runtime" custom install path...
		foreach(matlabPath ${MATLAB_DIRS})
			get_filename_component(matlabDirName ${matlabPath} NAME)
			if(${matlabDirName} MATCHES "MATLAB Component Runtime")
				file(GLOB NEW_MATLAB_DIRS "${matlabPath}/*")
				if(NEW_MATLAB_DIRS)
					list(REVERSE NEW_MATLAB_DIRS) ## in case of many matlab installation (get the last one)
					list(GET NEW_MATLAB_DIRS 0 MATLAB_DIR)
					break()
				endif()
			elseif(${matlabDirName} MATCHES "MATLAB Compiler Runtime")
				file(GLOB NEW_MATLAB_DIRS "${matlabPath}/*")
				if(NEW_MATLAB_DIRS)
					list(REVERSE NEW_MATLAB_DIRS) ## in case of many matlab installation (get the last one)
					list(GET NEW_MATLAB_DIRS 0 MATLAB_DIR)
					break()
				endif()
			endif()
		endforeach()
		## ...then if not found looking for last standard install of matlab
		if(NOT EXISTS ${MATLAB_DIR})
			list(REVERSE MATLAB_DIRS) ## in case of many matlab installation (get the last one)
			list(GET MATLAB_DIRS 0 MATLAB_DIR)
		endif()
	endif()
	set(MATLAB_INCLUDE_DIR "${MATLAB_DIR}/extern/include" CACHE PATH "Where we can find matlab include dir")
	if(NOT MATLAB_EXECUTABLE)
		find_program(MATLAB_EXECUTABLE matlab PATHS "$ENV{Path}")
	endif()
	set(MATLAB_EXECUTABLE "${MATLAB_EXECUTABLE}" CACHE PATH "Where we can find matlab exe file installation")
	if(EXISTS ${MATLAB_INCLUDE_DIR} AND EXISTS ${MATLAB_EXECUTABLE})
		set(MATLAB_FOUND ON)
	else()
		set(MATLAB_FOUND OFF)
	endif()

	## Find Matlab Runtime Compiler
	if(NOT EXISTS "${MATLAB_RC_DIR}/runtime")
		file(GLOB MATLAB_RC_VERSIONS_DIRS "$ENV{PROGRAMFILES}/MATLAB/MATLAB Compiler Runtime/*")
		IF(NOT MATLAB_RC_VERSIONS_DIRS)
			file(GLOB MATLAB_RC_VERSIONS_DIRS "$ENV{${PROGRAMFILES32}}/MATLAB/MATLAB Compiler Runtime/*")
			IF(NOT MATLAB_RC_VERSIONS_DIRS)
				file(GLOB MATLAB_RC_VERSIONS_DIRS "$ENV{ProgramW6432}/MATLAB/MATLAB Compiler Runtime/*")
			ENDIF()
		ENDIF()
		if(MATLAB_RC_VERSIONS_DIRS)
			foreach(matlabRCVersionDir ${MATLAB_RC_VERSIONS_DIRS})
				get_filename_component(MATLAB_RC_VERSION ${matlabRCVersionDir} NAME)
				if(WIN32 AND ${MATLAB_RC_VERSION} MATCHES "v716")
					set(MATLAB_RC_VERSIONS_DIR ${matlabRCVersionDir})
				endif()
			endforeach()
		endif()
		set(MATLAB_RC_DIR "${MATLAB_RC_VERSIONS_DIR}" CACHE PATH "Where we can find matlab runtime compiler installation" FORCE)
	endif()
	if(NOT EXISTS "${MATLAB_RC_DIR}/runtime")
		set(MATLAB_RC_FOUND OFF)
		set(MATLAB_RC_DIR "${MATLAB_RC_VERSIONS_DIR}" CACHE PATH "Where we can find matlab runtime compiler installation")
	else()
		set(MATLAB_RC_FOUND ON)
	endif()
	

elseif(UNIX)
	
	## Find Matlab
	file(GLOB MATLAB_EXE_LIST "${MATLAB_DIR}/matlab*")
	if(NOT MATLAB_EXE_LIST)
		file(GLOB MATLAB_EXE_LIST "/usr/bin/matlab*")
	endif()
	if(NOT MATLAB_EXE_LIST)
		file(GLOB MATLAB_EXE_LIST "/usr/local/bin/matlab*")
	endif()
	foreach(item ${MATLAB_EXE_LIST})
		if(IS_DIRECTORY ${item})
			list(REMOVE_ITEM MATLAB_EXE_LIST ${item})
		else()
			get_filename_component(itemExt ${item} EXT) ##as linux exe have no extension
			if(itemExt)
				list(REMOVE_ITEM MATLAB_EXE_LIST ${item})
			elseif(${item} MATCHES "matlab")
				set(MATLAB_EXECUTABLE ${item})
			endif()
		endif()
	endforeach()
	if(NOT MATLAB_EXECUTABLE)
		list(GET MATLAB_EXE_LIST 0 MATLAB_EXECUTABLE)
	endif()
	if(MATLAB_EXECUTABLE)
		set(MATLAB_FOUND ON)
	else()
		set(MATLAB_FOUND OFF)
	endif()
	set(MATLAB_EXECUTABLE "${MATLAB_EXECUTABLE}" CACHE PATH "Where we can find matlab exe file installation")

	## Find Matlab Runtime Compiler
	if(NOT EXISTS "${MATLAB_RC_DIR}/bin/matlab")
		file(GLOB MATLAB_RC_VERSIONS_DIRS "/usr/local/MATLAB/MATLAB_Compiler_Runtime/*")
		if(MATLAB_RC_VERSIONS_DIRS)
			foreach(matlabRCVersionDir ${MATLAB_RC_VERSIONS_DIRS})
				get_filename_component(MATLAB_RC_VERSION ${matlabRCVersionDir} NAME)
				message("MATLAB_RC_VERSION = ${MATLAB_RC_VERSION}")
				if(UNIX AND ${MATLAB_RC_VERSION} MATCHES "v80")
					set(MATLAB_RC_VERSIONS_DIR ${matlabRCVersionDir})
				endif()
			endforeach()
		endif()
		set(MATLAB_RC_DIR "${MATLAB_RC_VERSIONS_DIR}" CACHE PATH "Where we can find matlab runtime compiler installation")
	endif()
	if(NOT EXISTS ${MATLAB_RC_DIR}/bin/matlab)
		set(MATLAB_RC_FOUND OFF)
		set(MATLAB_RC_DIR "${MATLAB_RC_VERSIONS_DIR}" CACHE PATH "Where we can find matlab runtime compiler installation")
	else()
		set(MATLAB_RC_FOUND ON)
	endif()
				
endif()